### ISSUE TITLE
Add different formatting for segments created by !note command

### ISSUE THREAD

**Issue by CodemanCodes** [clarkio/stream-note-taker#7]
Once #6 is completed, it would also be helpful to have different formatting for segments created by the !mark command and segments created by the !note command.

Since !mark is intended for main segments of the stream, maybe like so:
**!mark Beginning of stream**

- !note We learned how x works
- !note Blah blah

**!mark Next main segment**

**Comment by clarkio** [comment]
Added in #8. Thanks for this suggestion as well!
